# Site settings
title: Samuel Hey | Web Dev
email: samuel.hey@gmail.com
url: samhey.io
description: "Web Developer"
skills: "Junior Web Developer"
meta_author: me

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: zuspadt_personal

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0b5484 #80B3FF
  # primary-rgb: "24,288,156" #"128,179,255"
  secondary: 35363D #FD6E8A
  secondary-dark: 35363D #A2122F

# Footer settings
footer:
  copyright: Samuel Hey
  # location: Glasgow
  social: Look Me Up
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/zuspadt79
  - title: linkedin
    url: http://www.linkedin.com/in/samuelhey
  - title: twitter
    url: http://twitter.com/zuspadt
  - title: facebook
    url: https://www.facebook.com/samuel.hey.3
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll


# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
